### ISSUE TITLE
Add typescript typings

### ISSUE THREAD

**Issue by Townsheriff** [saibotsivad/sign-aws-requests#1]
I think project is very nice and will make things much more easier. But it is missing typings. I think library is small we could migrate to typescript or create @types/sign-aws-requests module. What are your thoughts?

**Comment by saibotsivad** [comment]
I'm very unfamiliar with TS currently, and I don't have time to wade into learning it enough to figure it out, but I'll leave some notes here for my future self (or someone else who wants to contribute).

---

Based on conversations with other developers, it sounds like the thing to do is add a TS definition file, and point to it via the `package.json` file.

For example, looking at [httpie](https://github.com/lukeed/httpie/) it has `"types": "httpie.d.ts"` in the `package.json` and then the `httpie.d.ts` file is a hand written definition file.

One thing that I would definitely want is a way to test that the definitions were correct and valid TS. I know that some big names like Sindre use [tsd](https://www.npmjs.com/package/tsd), for example [here](https://github.com/sindresorhus/p-map/blob/master/index.test-d.ts), and others just make a [simple TS file](https://github.com/TehShrike/deepmerge/blob/master/test/typescript.ts) and make sure it [passes basic validation](https://github.com/TehShrike/deepmerge/blob/master/package.json#L25).

I would accept a pull request with a TS definition file that adds it to the `package.json` file under `types` (and also `files`), so long as it either used `tsd` or had some other basic validation.

**Comment by saibotsivad** [comment]
Closed with #8 🎉
